import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import PokeContextProvider  from '~/app/_contexts/PokeContext/Provider'
import { TRPCReactProvider } from "~/trpc/react";
import { defaultPokeState } from "./_contexts/PokeContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "PokeMemo | Matching Game",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/icon.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <PokeContextProvider>
          {children}
          </PokeContextProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
